name: beeapi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi==0.109.1
    - uvicorn[standard]==0.27.0
    - asyncpg==0.29.0
    - pydantic[email]==2.5.3
    - python-multipart==0.0.20
    - firebase-admin==6.1.0
    - python-dotenv==1.0.0
    - requests==2.31.0
    - pytest
    - httpx

# Para usar:
# conda env create -f environment.yml
# conda activate beeapi
# python main.py